VirtualProject/Controllers/Identities/ProfileEditeController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Net.Mail;
using VirtualProject.BL.Helper;
using VirtualProject.Models.Identity;
using VirtualProject.Models.Identity.ApplicationsIdentity;

namespace VirtualProject.Controllers.Identities
{
    [Authorize]
    public class ProfileEditeController : Controller
    {
        private readonly UserManager<ApplicationUser> userManager;

        public ProfileEditeController(UserManager<ApplicationUser> userManager)
        {
            this.userManager = userManager;
        }
        public async Task<IActionResult> Profile()
        {
            ApplicationUser user = await userManager.GetUserAsync(User);
            if (user == null)
            {
                return NotFound();
            }

            ProfileVM profile = new ProfileVM
            {
                FirstName = user.FirstName,
                LastName = user.LastName,
                Email = user.Email,
                PhoneNumber=user.PhoneNumber,
                ProfilePhotoName=user.ProfilePhoroUrl
            };

            return View(profile);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Profile(ProfileVM profileVM)
        {
            if (ModelState.IsValid)
            {
                ApplicationUser user = await userManager.GetUserAsync(User);
                if (user == null)
                {
                    return NotFound();
                }

                user.FirstName = profileVM.FirstName;
                user.LastName = profileVM.LastName;
                user.Email = profileVM.Email;
                user.UserName = profileVM.Email;
                user.PhoneNumber = profileVM.PhoneNumber;
                user.ProfilePhoroUrl = UploadFiles.SaveFile(profileVM.ProfilePhotoUrl,"Photos");
                // Update other profile properties

                IdentityResult result = await userManager.UpdateAsync(user);
                if (result.Succeeded)
                {
                    return RedirectToAction("Profile");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError("", error.Description);
                    }
                }

            }

            return View(profileVM);
        }


       
      
    }
}

VirtualProject/Views/ProfileEdite/Profile.cshtml
@model VirtualProject.Models.Identity.ProfileVM
@using Microsoft.AspNetCore.Identity


@{
    ViewBag.Title = "Profile";

}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">


    <!-- Custom fonts for this template-->
    <link href="~/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <!-- Custom styles for this template-->
    <link href="~/css/sb-admin-2.min.css" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

    <div class="container">

        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <form asp-controller="ProfileEdite" asp-action="Profile" method="post" enctype="multipart/form-data" class="form-group">
                            <!-- Nested Row within Card Body -->
                            <div class="row">
                               @* <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>*@
                                <div class="col-lg-6">
                                    <div class="p-5">
                                        @if (Model.ProfilePhotoName != null)
                                        {
                                            <img src="~/Files/Photos/@Model.ProfilePhotoName" width="295" height="300" />
                                        }
                                        else
                                        {
                                            <img src="~/img/undraw_profile.svg" width="295" height="300" />
                                        }
                                        <label asp-for="ProfilePhotoUrl" >Upload Photo</label>
                                        <input type="file" asp-for="ProfilePhotoUrl"/>
                                        <span asp-validation-for="ProfilePhotoUrl" class="text-danger"></span>
                                       
                                    </div>
                               </div>

                                <div class="col-lg-6">
                                    <div class="p-5">
                                        <div class="text-center">
                                            <h1 class="h4 text-gray-900 mb-4">Welcome Back!</h1>
                                        </div>


                                        <div asp-validation-summary="All"> </div>
                                        <div class="form-group row">
                                            <div class="col-sm-6 mb-3 mb-sm-0">
                                                <input type="text" class="form-control form-control-user" asp-for="FirstName">
                                                <span asp-validation-for="FirstName" class="text-danger"></span>
                                            </div>
                                            <div class="col-sm-6">
                                                <input type="text" class="form-control form-control-user" asp-for="LastName">
                                                <span asp-validation-for="LastName" class="text-danger"></span>
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <input type="email" class="form-control form-control-user" asp-for="Email" aria-describedby="emailHelp">
                                            <span asp-validation-for="Email" class="text-danger"> </span>
                                        </div>
                                        <br />
                                        <div class="form-group">
                                            <input type="number" asp-for="PhoneNumber" class="form-control form-control-user">
                                            <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                                        </div>
                                        <br />

                                        <input type="submit" value="Save" class="btn btn-primary btn-user btn-block" />
                                        <br /> <br />




                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>

            </div>

        </div>

    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="~/vendor/jquery/jquery.min.js"></script>
    <script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/jquery-validate/jquery.validate.min.js"></script>
    <script src="~/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <!-- Core plugin JavaScript-->
    <script src="~/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/js/sb-admin-2.min.js"></script>

</body>

</html>